// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4g6lKd6v-kFlwTCQ8Qtm_nrh1DtUvuEI',
    appId: '1:736668030:web:2b638daf6d3304e2866b2f',
    messagingSenderId: '736668030',
    projectId: 'projet-8e095',
    authDomain: 'projet-8e095.firebaseapp.com',
    storageBucket: 'projet-8e095.appspot.com',
    measurementId: 'G-ZTSM4KM5J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6FKpmj-6IEh4kPJkwtSFRyFfl9sHruU',
    appId: '1:736668030:android:c744e5a0032e63c5866b2f',
    messagingSenderId: '736668030',
    projectId: 'projet-8e095',
    storageBucket: 'projet-8e095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIxFhgf2f6uzhvaPycZEUw1tKAzBMjR8M',
    appId: '1:736668030:ios:bb76d2cc5d10a72f866b2f',
    messagingSenderId: '736668030',
    projectId: 'projet-8e095',
    storageBucket: 'projet-8e095.appspot.com',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIxFhgf2f6uzhvaPycZEUw1tKAzBMjR8M',
    appId: '1:736668030:ios:0e817e6b6cdfb74f866b2f',
    messagingSenderId: '736668030',
    projectId: 'projet-8e095',
    storageBucket: 'projet-8e095.appspot.com',
    iosBundleId: 'com.example.projet.RunnerTests',
  );
}
